const fs = require('fs');
const path = require('path');

// 读取原始备份文件
const dataPath = path.join(__dirname, 'product-data.json.backup');
const rawData = fs.readFileSync(dataPath, 'utf8');
const data = JSON.parse(rawData);

// 专业俄文汽车零部件翻译映射表（完整版）
const translationMap = {
    // === 完整产品名称优先 ===
    'Oil Cooler Pipe Seal': 'Уплотнительное кольцо трубы масляного охладителя',
    'Fuel Injector Seal Lower': 'Нижнее уплотнительное кольцо топливной форсунки',
    'Fuel Injector Seal Upper': 'Верхнее уплотнительное кольцо топливной форсунки',
    'Oil Return Pipe': 'Труба возврата масла',
    'High Pressure Pump': 'Насос высокого давления',
    'Oil Water Separator': 'Сепаратор масла и воды',
    'Camshaft Solenoid Valve': 'Соленоидный клапан распределительного вала',
    'EGR Pipe': 'Труба EGR',
    'Oil Dipstick': 'Щуп уровня масла',
    'Exhaust System': 'Система выхлопа',
    'Port Gasket': 'Прокладка порта',
    'Power Steering': 'Гидроусилитель руля',
    'Expansion Tank': 'Расширительный бачок',
    'Handbrake Switch': 'Переключатель ручного тормоза',
    'Combination Switch': 'Комбинированный переключатель',
    'Trunk Switch': 'Переключатель багажника',
    'Front Wheel Bearing': 'Подшипник переднего колеса',
    'Window Switch': 'Переключатель стеклоподъемника',
    'Air Pump': 'Воздушный насос',
    'Left Front Window Switch': 'Переключатель левого переднего стеклоподъемника',
    'Fuel Hose': 'Топливный шланг',
    'Coolant Return Pipe': 'Труба возврата охлаждающей жидкости',
    'Transmission Cooler Pipe': 'Труба охладителя коробки передач',
    'Turbocharger Pipe': 'Труба турбокомпрессора',
    'Intake Pipe': 'Впускная труба',
    'Intercooler Pipe': 'Труба интеркулера',
    'Front Boot': 'Пыльник передний',
    'Rear Boot': 'Пыльник задний',
    'Pressure Sensor': 'Датчик давления',
    'AC Pipe': 'Труба кондиционера',
    'Emission Pipe': 'Труба системы выпуска',
    'Carbon Canister Valve': 'Клапан адсорбера',
    'Electric Fan': 'Электровентилятор',
    'Front Bump Stop': 'Отбойник передний',
    'Rear Bump Stop': 'Отбойник задний',
    'Carbon Canister': 'Адсорбер',
    'EGR Valve': 'Клапан EGR',
    'Vent Valve': 'Вентиляционный клапан',
    'Exhaust Unit': 'Блок выхлопной системы',
    'Heater Valve': 'Клапан отопителя',
    'Auxiliary Water Pump': 'Вспомогательный водяной насос',
    'Camshaft Position Sensor': 'Датчик положения распределительного вала',
    'Oil Pressure Sensor': 'Датчик давления масла',
    'ABS Sensor': 'Датчик ABS',
    'Height Sensor': 'Датчик высоты',
    'Intake Pressure Sensor': 'Датчик давления во впускном коллекторе',
    'Washer Reservoir': 'Бачок омывателя',
    'Transmission Oil Pan': 'Поддон масляный коробки передач',
    'ABS Wire': 'Провод датчика ABS',
    'Eccentric Shaft Sensor': 'Датчик эксцентрикового вала',
    'Cylinder Head': 'Головка блока цилиндров',
    'Oil Filter Housing': 'Корпус масляного фильтра',
    'Water Pump': 'Водяной насос',
    'Oil Pan': 'Поддон масляный',
    'Vent Tube': 'Вентиляционная труба',
    'Cutoff Valve': 'Отсечной клапан',
    'Exhaust Manifold': 'Впускной коллектор',
    'Throttle Body': 'Дроссельная заслонка',
    'Door Handle': 'Ручка двери',
    'Electronic Water Pump': 'Электрический водяной насос',
    'Hydraulic Valve': 'Гидравлический клапан',
    'Chain Guide': 'Направляющая цепи',
    'Oil Drain': 'Слив масла',
    'Air Filter': 'Воздушный фильтр',
    'Fuel Filter': 'Топливный фильтр',
    'Oil Filter': 'Масляный фильтр',
    'Cabin Filter': 'Фильтр салона',
    'Brake Pad': 'Тормозные колодки',
    'Brake Disc': 'Тормозной диск',
    'Spark Plug': 'Свеча зажигания',
    'Timing Belt': 'Ремень ГРМ',
    'Timing Chain': 'Цепь ГРМ',
    'Clutch Kit': 'Комплект сцепления',
    'Shock Absorber': 'Амортизатор',
    'Control Arm': 'Рычаг подвески',
    'Ball Joint': 'Шаровой шарнир',
    'Tie Rod': 'Тяга рулевая',
    'Axle Shaft': 'Вал полуоси',
    'Wheel Hub': 'Ступица колеса',
    'Drive Shaft': 'Карданный вал',
    'CV Joint': 'ШРУС',
    'Engine Mount': 'Подушка двигателя',
    'Transmission Mount': 'Подушка коробки передач',
    'Radiator Hose': 'Шланг радиатора',
    'Heater Hose': 'Шланг отопителя',
    'Fuel Injector': 'Топливная форсунка',
    'Ignition Coil': 'Катушка зажигания',
    'Oxygen Sensor': 'Лямбда-зонд',
    'Mass Air Flow Sensor': 'Датчик расхода воздуха',
    'Throttle Position Sensor': 'Датчик положения дроссельной заслонки',
    'Crankshaft Position Sensor': 'Датчик положения коленвала',
    'Camshaft Position Sensor': 'Датчик положения распредвала',
    'Knock Sensor': 'Датчик детонации',
    'Coolant Temperature Sensor': 'Датчик температуры охлаждающей жидкости',
    'Oil Pressure Sensor': 'Датчик давления масла',
    'Fuel Pressure Sensor': 'Датчик давления топлива',
    'MAP Sensor': 'Датчик абсолютного давления',
    'Idle Air Control Valve': 'Клапан регулировки холостого хода',
    'EGR Valve': 'Клапан EGR',
    'PCV Valve': 'Клапан вентиляции картерных газов',
    'Thermostat': 'Термостат',
    'Water Pump': 'Водяной насос',
    'Radiator': 'Радиатор',
    'Condenser': 'Конденсатор',
    'Evaporator': 'Испаритель',
    'Compressor': 'Компрессор',
    'Receiver Drier': 'Ресивер-осушитель',
    'Expansion Valve': 'Расширительный клапан',
    'Orifice Tube': 'Дроссельная трубка',
    'Accumulator': 'Аккумулятор',
    'Blower Motor': 'Мотор вентилятора',
    'Heater Core': 'Радиатор отопителя',
    'A/C Hose': 'Шланг кондиционера',
    'A/C Line': 'Линия кондиционера',
    'Power Steering Pump': 'Насос гидроусилителя руля',
    'Power Steering Hose': 'Шланг гидроусилителя руля',
    'Power Steering Rack': 'Рейка гидроусилителя руля',
    'Brake Master Cylinder': 'Главный тормозной цилиндр',
    'Brake Caliper': 'Суппорт тормозной',
    'Brake Hose': 'Тормозной шланг',
    'Brake Line': 'Тормозная линия',
    'Wheel Cylinder': 'Колесный тормозной цилиндр',
    'Parking Brake Cable': 'Трос ручного тормоза',
    'Clutch Master Cylinder': 'Главный цилиндр сцепления',
    'Clutch Slave Cylinder': 'Рабочий цилиндр сцепления',
    'Clutch Hose': 'Шланг сцепления',
    'Flywheel': 'Маховик',
    'Pressure Plate': 'Корзина сцепления',
    'Clutch Disc': 'Диск сцепления',
    'Throw Out Bearing': 'Выжимной подшипник',
    'Pilot Bushing': 'Направляющая втулка',
    'Manual Transmission': 'Механическая коробка передач',
    'Automatic Transmission': 'Автоматическая коробка передач',
    'CVT Transmission': 'Вариатор',
    'Transfer Case': 'Раздаточная коробка',
    'Differential': 'Дифференциал',
    'Drive Axle': 'Ведущий мост',
    'Front Differential': 'Передний дифференциал',
    'Rear Differential': 'Задний дифференциал',
    'Axle Shaft': 'Полуось',
    'CV Joint': 'ШРУС',
    'Inner CV Joint': 'Внутренний ШРУС',
    'Outer CV Joint': 'Внешний ШРУС',
    'CV Boot': 'Пыльник ШРУС',
    'Wheel Bearing': 'Подшипник колеса',
    'Wheel Hub': 'Ступица колеса',
    'Wheel Stud': 'Шпилька колеса',
    'Wheel Nut': 'Гайка колеса',
    'Tire Pressure Sensor': 'Датчик давления в шинах',
    'TPMS Sensor': 'Датчик TPMS',
    'Suspension': 'Подвеска',
    'Strut': 'Стойка',
    'Coil Spring': 'Пружина',
    'Leaf Spring': 'Рессора',
    'Control Arm': 'Рычаг',
    'Upper Control Arm': 'Верхний рычаг',
    'Lower Control Arm': 'Нижний рычаг',
    'Ball Joint': 'Шаровой шарнир',
    'Tie Rod End': 'Наконечник рулевой тяги',
    'Inner Tie Rod': 'Внутренняя рулевая тяга',
    'Outer Tie Rod': 'Внешняя рулевая тяга',
    'Sway Bar': 'Стабилизатор поперечной устойчивости',
    'Sway Bar Link': 'Стойка стабилизатора',
    'Bushing': 'Втулка',
    'Engine': 'Двигатель',
    'Cylinder Block': 'Блок цилиндров',
    'Cylinder Head': 'Головка блока цилиндров',
    'Piston': 'Поршень',
    'Piston Ring': 'Поршневое кольцо',
    'Connecting Rod': 'Шатун',
    'Crankshaft': 'Коленчатый вал',
    'Camshaft': 'Распределительный вал',
    'Valve': 'Клапан',
    'Valve Spring': 'Пружина клапана',
    'Valve Stem Seal': 'Сальник клапана',
    'Timing Chain': 'Цепь ГРМ',
    'Timing Belt': 'Ремень ГРМ',
    'Timing Cover': 'Крышка ГРМ',
    'Oil Pan': 'Поддон масляный',
    'Oil Pump': 'Масляный насос',
    'Oil Pickup Tube': 'Трубка маслозаборника',
    'Oil Filter': 'Масляный фильтр',
    'Oil Cooler': 'Масляный охладитель',
    'Oil Pressure Sensor': 'Датчик давления масла',
    'Oil Level Sensor': 'Датчик уровня масла',
    'Oil Temperature Sensor': 'Датчик температуры масла',
    'Water Pump': 'Водяной насос',
    'Thermostat': 'Термостат',
    'Radiator': 'Радиатор',
    'Radiator Fan': 'Вентилятор радиатора',
    'Radiator Hose': 'Шланг радиатора',
    'Heater Hose': 'Шланг отопителя',
    'Heater Core': 'Радиатор отопителя',
    'Expansion Tank': 'Расширительный бачок',
    'Coolant Temperature Sensor': 'Датчик температуры охлаждающей жидкости',
    'Coolant Level Sensor': 'Датчик уровня охлаждающей жидкости',
    'Fuel Pump': 'Топливный насос',
    'Fuel Filter': 'Топливный фильтр',
    'Fuel Injector': 'Топливная форсунка',
    'Fuel Rail': 'Топливная рампа',
    'Fuel Pressure Regulator': 'Регулятор давления топлива',
    'Fuel Tank': 'Топливный бак',
    'Fuel Sending Unit': 'Датчик уровня топлива',
    'Fuel Cap': 'Крышка топливного бака',
    'Fuel Line': 'Топливная линия',
    'Fuel Hose': 'Топливный шланг',
    'Air Filter': 'Воздушный фильтр',
    'Air Intake Hose': 'Шланг воздухозаборника',
    'Air Intake Tube': 'Трубка воздухозаборника',
    'Mass Air Flow Sensor': 'Датчик расхода воздуха',
    'Throttle Body': 'Дроссельная заслонка',
    'Intake Manifold': 'Впускной коллектор',
    'Exhaust Manifold': 'Выпускной коллектор',
    'Catalytic Converter': 'Катализатор',
    'Muffler': 'Глушитель',
    'Resonator': 'Резонатор',
    'Exhaust Pipe': 'Выхлопная труба',
    'Exhaust System': 'Система выхлопа',
    'Oxygen Sensor': 'Лямбда-зонд',
    'EGR Valve': 'Клапан EGR',
    'EGR Cooler': 'Охладитель EGR',
    'Turbocharger': 'Турбокомпрессор',
    'Supercharger': 'Компрессор',
    'Intercooler': 'Интеркулер',
    'Wastegate': 'Водяной затвор',
    'Blow Off Valve': 'Клапан сброса давления',
    'Ignition Coil': 'Катушка зажигания',
    'Spark Plug': 'Свеча зажигания',
    'Spark Plug Wire': 'Провод свечи зажигания',
    'Distributor': 'Распределитель зажигания',
    'Distributor Cap': 'Крышка распределителя',
    'Rotor': 'Ротор',
    'Ignition Module': 'Модуль зажигания',
    'PCM': 'ЭБУ',
    'ECU': 'ЭБУ',
    'Engine Control Module': 'Модуль управления двигателем',
    'Body Control Module': 'Модуль управления кузовом',
    'Transmission Control Module': 'Модуль управления коробкой передач',
    'ABS Module': 'Модуль ABS',
    'Airbag Module': 'Модуль подушек безопасности',
    'Battery': 'Аккумулятор',
    'Alternator': 'Генератор',
    'Starter': 'Стартер',
    'Starter Solenoid': 'Соленоид стартера',
    'Ignition Switch': 'Выключатель зажигания',
    'Key Fob': 'Брелок',
    'Remote Start': 'Дистанционный запуск',
    'Wiper Motor': 'Мотор стеклоочистителя',
    'Wiper Blade': 'Щетка стеклоочистителя',
    'Washer Pump': 'Насос омывателя',
    'Washer Reservoir': 'Бачок омывателя',
    'Washer Nozzle': 'Форсунка омывателя',
    'Horn': 'Сигнал',
    'Headlight': 'Фара',
    'Headlight Bulb': 'Лампа фары',
    'Headlight Assembly': 'Фара в сборе',
    'Tail Light': 'Задний фонарь',
    'Tail Light Bulb': 'Лампа заднего фонаря',
    'Turn Signal': 'Повторитель поворота',
    'Stop Light': 'Стоп-сигнал',
    'Fog Light': 'Противотуманная фара',
    'Daytime Running Light': 'Дневные ходовые огни',
    'LED': 'LED',
    'HID': 'Гидрогенидная',
    'Halogen': 'Галогенная',
    'Xenon': 'Ксеноновая',
    'Door Handle': 'Ручка двери',
    'Door Lock': 'Замок двери',
    'Door Lock Actuator': 'Привод замка двери',
    'Door Hinge': 'Петля двери',
    'Door Check': 'Ограничитель двери',
    'Window Regulator': 'Стеклоподъемник',
    'Window Motor': 'Мотор стеклоподъемника',
    'Window Switch': 'Переключатель стеклоподъемника',
    'Mirror': 'Зеркало',
    'Side Mirror': 'Боковое зеркало',
    'Rear View Mirror': 'Внутреннее зеркало',
    'Mirror Glass': 'Стекло зеркала',
    'Mirror Cover': 'Крышка зеркала',
    'Mirror Switch': 'Переключатель зеркала',
    'Seat': 'Сиденье',
    'Seat Belt': 'Ремень безопасности',
    'Seat Belt Buckle': 'Пряжка ремня безопасности',
    'Seat Belt Retractor': 'Натяжитель ремня безопасности',
    'Seat Heater': 'Подогрев сиденья',
    'Seat Adjuster': 'Регулятор сиденья',
    'Headrest': 'Подголовник',
    'Armrest': 'Подлокотник',
    'Dashboard': 'Панель приборов',
    'Instrument Cluster': 'Комбинация приборов',
    'Gauge': 'Указатель',
    'Speedometer': 'Спидометр',
    'Tachometer': 'Тахометр',
    'Fuel Gauge': 'Указатель уровня топлива',
    'Temperature Gauge': 'Указатель температуры',
    'Oil Pressure Gauge': 'Указатель давления масла',
    'Voltmeter': 'Вольтметр',
    'Warning Light': 'Контрольная лампа',
    'Check Engine Light': 'Лампа Check Engine',
    'ABS Light': 'Лампа ABS',
    'Airbag Light': 'Лампа подушек безопасности',
    'Steering Wheel': 'Рулевое колесо',
    'Steering Column': 'Рулевой столб',
    'Steering Rack': 'Рулевая рейка',
    'Power Steering Pump': 'Насос гидроусилителя руля',
    'Tie Rod': 'Рулевая тяга',
    'Tie Rod End': 'Наконечник рулевой тяги',
    'Ball Joint': 'Шаровой шарнир',
    'Control Arm': 'Рычаг',
    'Sway Bar': 'Стабилизатор',
    'Sway Bar Link': 'Стойка стабилизатора',
    'Strut': 'Стойка',
    'Shock Absorber': 'Амортизатор',
    'Coil Spring': 'Пружина',
    'Leaf Spring': 'Рессора',
    'Bushing': 'Втулка',
    'Wheel Bearing': 'Подшипник колеса',
    'Wheel Hub': 'Ступица колеса',
    'Wheel Stud': 'Шпилька колеса',
    'Wheel Nut': 'Гайка колеса',
    'Tire': 'Шина',
    'Wheel': 'Диск',
    'Rim': 'Обод',
    'Hubcap': 'Колпак колеса',
    'Center Cap': 'Центральный колпак',
    'Lug Nut': 'Гайка колеса',
    'Lug Stud': 'Шпилька колеса',
    'Brake Pad': 'Тормозные колодки',
    'Brake Shoe': 'Тормозные колодки (барабанные)',
    'Brake Disc': 'Тормозной диск',
    'Brake Drum': 'Тормозной барабан',
    'Brake Caliper': 'Суппорт тормозной',
    'Brake Master Cylinder': 'Главный тормозной цилиндр',
    'Brake Booster': 'Усилитель тормозов',
    'Brake Hose': 'Тормозной шланг',
    'Brake Line': 'Тормозная линия',
    'Wheel Cylinder': 'Колесный тормозной цилиндр',
    'Parking Brake Cable': 'Трос ручного тормоза',
    'Parking Brake Shoes': 'Колодки ручного тормоза',
    'Clutch Kit': 'Комплект сцепления',
    'Clutch Disc': 'Диск сцепления',
    'Pressure Plate': 'Корзина сцепления',
    'Flywheel': 'Маховик',
    'Throw Out Bearing': 'Выжимной подшипник',
    'Clutch Master Cylinder': 'Главный цилиндр сцепления',
    'Clutch Slave Cylinder': 'Рабочий цилиндр сцепления',
    'Clutch Hose': 'Шланг сцепления',
    'Manual Transmission': 'Механическая коробка передач',
    'Automatic Transmission': 'Автоматическая коробка передач',
    'CVT': 'Вариатор',
    'Transfer Case': 'Раздаточная коробка',
    'Differential': 'Дифференциал',
    'Drive Shaft': 'Карданный вал',
    'CV Joint': 'ШРУС',
    'CV Boot': 'Пыльник ШРУС',
    'Axle Shaft': 'Полуось',
    'Wheel Bearing': 'Подшипник колеса',
    'Engine Mount': 'Подушка двигателя',
    'Transmission Mount': 'Подушка коробки передач',
    'Torque Strut': 'Торсионная тяга',
    'Radiator Support': 'Оправа радиатора',
    'Bumper': 'Бампер',
    'Front Bumper': 'Передний бампер',
    'Rear Bumper': 'Задний бампер',
    'Bumper Cover': 'Крышка бампера',
    'Bumper Reinforcement': 'Усилитель бампера',
    'Bumper Bracket': 'Кронштейн бампера',
    'Fender': 'Крыло',
    'Front Fender': 'Переднее крыло',
    'Rear Fender': 'Заднее крыло',
    'Fender Liner': 'Подкрылок',
    'Hood': 'Капот',
    'Trunk Lid': 'Крышка багажника',
    'Deck Lid': 'Крышка багажника',
    'Tailgate': 'Дверь багажника',
    'Door': 'Дверь',
    'Front Door': 'Передняя дверь',
    'Rear Door': 'Задняя дверь',
    'Door Shell': 'Облицовка двери',
    'Door Skin': 'Панель двери',
    'Door Frame': 'Рамка двери',
    'Door Seal': 'Уплотнение двери',
    'Weatherstrip': 'Уплотнение',
    'Windshield': 'Лобовое стекло',
    'Rear Window': 'Заднее стекло',
    'Door Glass': 'Стекло двери',
    'Quarter Glass': 'Малое стекло',
    'Vent Glass': 'Вентиляционное стекло',
    'Sunroof': 'Люк',
    'Moonroof': 'Люк',
    'Convertible Top': 'Складная крыша',
    'Roof Rack': 'Багажник на крышу',
    'Roof Rail': 'Рейлинг на крыше',
    'Grille': 'Решетка радиатора',
    'Upper Grille': 'Верхняя решетка',
    'Lower Grille': 'Нижняя решетка',
    'Headlight': 'Фара',
    'Tail Light': 'Задний фонарь',
    'Fog Light': 'Противотуманная фара',
    'Side Marker Light': 'Боковой габарит',
    'License Plate Light': 'Фонарь подсветки номера',
    'Third Brake Light': 'Дополнительный стоп-сигнал',
    'Reverse Light': 'Фонарь заднего хода',
    'Turn Signal': 'Повторитель поворота',
    'Hood': 'Капот',
    'Hood Latch': 'Замок капота',
    'Hood Cable': 'Трос капота',
    'Hood Hinge': 'Петля капота',
    'Trunk Latch': 'Замок багажника',
    'Trunk Cable': 'Трос багажника',
    'Trunk Hinge': 'Петля багажника',
    'Tailgate Latch': 'Замок двери багажника',
    'Door Latch': 'Замок двери',
    'Door Lock Actuator': 'Привод замка двери',
    'Door Striker': 'Защелка двери',
    'Door Check': 'Ограничитель двери',
    'Door Hinge': 'Петля двери',
    'Door Panel': 'Обшивка двери',
    'Door Armrest': 'Подлокотник двери',
    'Door Handle': 'Ручка двери',
    'Exterior Door Handle': 'Внешняя ручка двери',
    'Interior Door Handle': 'Внутренняя ручка двери',
    'Door Mirror': 'Боковое зеркало',
    'Side Mirror': 'Боковое зеркало',
    'Rear View Mirror': 'Внутреннее зеркало',
    'Mirror Glass': 'Стекло зеркала',
    'Mirror Cover': 'Крышка зеркала',
    'Mirror Housing': 'Корпус зеркала',
    'Mirror Switch': 'Переключатель зеркала',
    'Power Mirror': 'Электрическое зеркало',
    'Heated Mirror': 'Зеркало с подогревом',
    'Manual Mirror': 'Ручное зеркало',
    'Towing Mirror': 'Зеркало для прицепа',
    'Seat': 'Сиденье',
    'Front Seat': 'Переднее сиденье',
    'Rear Seat': 'Заднее сиденье',
    'Seat Cushion': 'Подушка сиденья',
    'Seat Back': 'Спинка сиденья',
    'Seat Headrest': 'Подголовник',
    'Seat Cover': 'Чехол сиденья',
    'Seat Foam': 'Пенополиуретан сиденья',
    'Seat Frame': 'Каркас сиденья',
    'Seat Track': 'Направляющая сиденья',
    'Seat Motor': 'Мотор сиденья',
    'Seat Heater': 'Подогрев сиденья',
    'Seat Cooler': 'Охлаждение сиденья',
    'Seat Adjuster': 'Регулятор сиденья',
    'Seat Lumbar': 'Поддержка поясницы',
    'Seat Side Airbag': 'Боковая подушка безопасности сиденья',
    'Seat Belt': 'Ремень безопасности',
    'Front Seat Belt': 'Передний ремень безопасности',
    'Rear Seat Belt': 'Задний ремень безопасности',
    'Seat Belt Buckle': 'Пряжка ремня безопасности',
    'Seat Belt Retractor': 'Натяжитель ремня безопасности',
    'Seat Belt Pretensioner': 'Преднатяжитель ремня безопасности',
    'Seat Belt Height Adjuster': 'Регулятор высоты ремня безопасности',
    'Airbag': 'Подушка безопасности',
    'Driver Airbag': 'Подушка безопасности водителя',
    'Passenger Airbag': 'Подушка безопасности пассажира',
    'Side Airbag': 'Боковая подушка безопасности',
    'Curtain Airbag': 'Шторка безопасности',
    'Knee Airbag': 'Подушка безопасности для коленей',
    'Airbag Control Module': 'Модуль управления подушками безопасности',
    'Airbag Sensor': 'Датчик подушек безопасности',
    'Clock Spring': 'Спиральный шлейф',
    'Instrument Cluster': 'Комбинация приборов',
    'Speedometer': 'Спидометр',
    'Tachometer': 'Тахометр',
    'Fuel Gauge': 'Указатель уровня топлива',
    'Temperature Gauge': 'Указатель температуры',
    'Oil Pressure Gauge': 'Указатель давления масла',
    'Voltmeter': 'Вольтметр',
    'Odometer': 'Одометр',
    'Trip Odometer': 'Суточный одометр',
    'Warning Light': 'Контрольная лампа',
    'Indicator Light': 'Индикаторная лампа',
    'Check Engine Light': 'Лампа Check Engine',
    'ABS Light': 'Лампа ABS',
    'Airbag Light': 'Лампа подушек безопасности',
    'Brake Light': 'Лампа тормозной системы',
    'Oil Light': 'Лампа давления масла',
    'Battery Light': 'Лампа аккумулятора',
    'Temperature Light': 'Лампа температуры',
    'Fuel Light': 'Лампа уровня топлива',
    'Door Ajar Light': 'Лампа открытой двери',
    'Seat Belt Light': 'Лампа ремня безопасности',
    'Traction Control Light': 'Лампа системы стабилизации',
    'ESP Light': 'Лампа ESP',
    'Hill Hold Light': 'Лампа удержания на подъеме',
    'TPMS Light': 'Лампа TPMS',
    'Cruise Control Light': 'Лампа круиз-контроля',
    'High Beam Light': 'Лампа дальнего света',
    'Turn Signal Light': 'Лампа поворота',
    'Hazard Light': 'Лампа аварийной сигнализации',
    'Steering Wheel': 'Рулевое колесо',
    'Steering Wheel Cover': 'Обшивка рулевого колеса',
    'Steering Wheel Control': 'Управление на руле',
    'Airbag Steering Wheel': 'Рулевое колесо с подушкой безопасности',
    'Steering Column': 'Рулевой столб',
    'Ignition Lock': 'Замок зажигания',
    'Ignition Switch': 'Выключатель зажигания',
    'Steering Lock': 'Блокировка руля',
    'Turn Signal Switch': 'Переключатель поворотов',
    'Wiper Switch': 'Переключатель стеклоочистителя',
    'Headlight Switch': 'Выключатель фар',
    'Combination Switch': 'Комбинированный переключатель',
    'Cruise Control Switch': 'Переключатель круиз-контроля',
    'Steering Wheel Audio Control': 'Управление аудио на руле',
    'Steering Wheel Phone Control': 'Управление телефоном на руле',
    'Steering Wheel Heat': 'Подогрев рулевого колеса',
    'Power Steering': 'Гидроусилитель руля',
    'Electric Power Steering': 'Электрогидроусилитель руля',
    'Steering Rack': 'Рулевая рейка',
    'Steering Gear': 'Рулевой механизм',
    'Power Steering Pump': 'Насос гидроусилителя руля',
    'Power Steering Hose': 'Шланг гидроусилителя руля',
    'Power Steering Fluid': 'Жидкость гидроусилителя руля',
    'Tie Rod': 'Рулевая тяга',
    'Tie Rod End': 'Наконечник рулевой тяги',
    'Inner Tie Rod': 'Внутренняя рулевая тяга',
    'Outer Tie Rod': 'Внешняя рулевая тяга',
    'Ball Joint': 'Шаровой шарнир',
    'Control Arm': 'Рычаг',
    'Upper Control Arm': 'Верхний рычаг',
    'Lower Control Arm': 'Нижний рычаг',
    'Front Control Arm': 'Передний рычаг',
    'Rear Control Arm': 'Задний рычаг',
    'Wishbone': 'Рычаг',
    'MacPherson Strut': 'Стойка Макферсон',
    'Coilover': 'Койловер',
    'Air Suspension': 'Пневмоподвеска',
    'Hydraulic Suspension': 'Гидроподвеска',
    'Active Suspension': 'Активная подвеска',
    'Sway Bar': 'Стабилизатор поперечной устойчивости',
    'Sway Bar Link': 'Стойка стабилизатора',
    'Stabilizer Bar': 'Стабилизатор',
    'Stabilizer Link': 'Стойка стабилизатора',
    'Strut': 'Стойка',
    'Strut Mount': 'Опора стойки',
    'Strut Bearing': 'Подшипник стойки',
    'Shock Absorber': 'Амортизатор',
    'Gas Shock': 'Газовый амортизатор',
    'Hydraulic Shock': 'Гидравлический амортизатор',
    'Coil Spring': 'Пружина',
    'Leaf Spring': 'Рессора',
    'Air Spring': 'Пневмопружина',
    'Helper Spring': 'Дополнительная пружина',
    'Lowering Spring': 'Понижающая пружина',
    'Lift Spring': 'Поднимающая пружина',
    'Bushing': 'Втулка',
    'Control Arm Bushing': 'Втулка рычага',
    'Sway Bar Bushing': 'Втулка стабилизатора',
    'Leaf Spring Bushing': 'Втулка рессоры',
    'Panhard Rod': 'Панхард',
    'Track Bar': 'Тяга',
    'Torque Arm': 'Торсионная тяга',
    'Radius Arm': 'Радиусная тяга',
    'Wheel Bearing': 'Подшипник колеса',
    'Wheel Hub': 'Ступица колеса',
    'Wheel Stud': 'Шпилька колеса',
    'Wheel Nut': 'Гайка колеса',
    'Hub Assembly': 'Ступица в сборе',
    'Wheel Bearing Hub': 'Ступица с подшипником',
    'Axle Shaft': 'Полуось',
    'CV Joint': 'ШРУС',
    'Inner CV Joint': 'Внутренний ШРУС',
    'Outer CV Joint': 'Внешний ШРУС',
    'CV Boot': 'Пыльник ШРУС',
    'Drive Shaft': 'Карданный вал',
    'Propeller Shaft': 'Карданный вал',
    'U-Joint': 'Крестовина',
    'Universal Joint': 'Универсальный шарнир',
    'Center Support Bearing': 'Промежуточный подшипник',
    'Differential': 'Дифференциал',
    'Front Differential': 'Передний дифференциал',
    'Rear Differential': 'Задний дифференциал',
    'Limited Slip Differential': 'Самоблокирующийся дифференциал',
    'Locking Differential': 'Блокируемый дифференциал',
    'Differential Cover': 'Крышка дифференциала',
    'Differential Pinion Seal': 'Сальник редуктора',
    'Differential Bearing': 'Подшипник редуктора',
    'Ring and Pinion': 'Главная пара',
    'Axle Ratio': 'Передаточное число',
    'Gear Ratio': 'Передаточное число',
    'Transfer Case': 'Раздаточная коробка',
    'Transfer Case Shift Motor': 'Мотор переключения раздаточной коробки',
    'Transfer Case Control Module': 'Модуль управления раздаточной коробкой',
    '4WD': 'Полный привод',
    'AWD': 'Полный привод',
    'FWD': 'Передний привод',
    'RWD': 'Задний привод',
    'Engine': 'Двигатель',
    'Cylinder Block': 'Блок цилиндров',
    'Cylinder Head': 'Головка блока цилиндров',
    'Cylinder Head Gasket': 'Прокладка ГБЦ',
    'Valve Cover': 'Крышка клапанов',
    'Valve Cover Gasket': 'Прокладка крышки клапанов',
    'Timing Cover': 'Крышка ГРМ',
    'Timing Cover Gasket': 'Прокладка крышки ГРМ',
    'Oil Pan': 'Поддон масляный',
    'Oil Pan Gasket': 'Прокладка поддона',
    'Oil Pump': 'Масляный насос',
    'Oil Pump Pickup Tube': 'Трубка маслозаборника',
    'Oil Filter': 'Масляный фильтр',
    'Oil Cooler': 'Масляный охладитель',
    'Oil Cooler Line': 'Линия масляного охладителя',
    'Oil Cooler Hose': 'Шланг масляного охладителя',
    'Oil Pressure Sensor': 'Датчик давления масла',
    'Oil Level Sensor': 'Датчик уровня масла',
    'Oil Temperature Sensor': 'Датчик температуры масла',
    'Oil Dipstick': 'Щуп уровня масла',
    'Oil Dipstick Tube': 'Трубка щупа уровня масла',
    'Piston': 'Поршень',
    'Piston Ring': 'Поршневое кольцо',
    'Piston Pin': 'Поршневой палец',
    'Connecting Rod': 'Шатун',
    'Connecting Rod Bearing': 'Вкладыш шатуна',
    'Crankshaft': 'Коленчатый вал',
    'Crankshaft Bearing': 'Вкладыш коленвала',
    'Main Bearing': 'Коренной подшипник',
    'Connecting Rod Bearing': 'Шатунный подшипник',
    'Thrust Washer': 'Упорный полукольцо',
    'Crankshaft Pulley': 'Шкив коленвала',
    'Harmonic Balancer': 'Гаситель колебаний',
    'Camshaft': 'Распределительный вал',
    'Camshaft Bearing': 'Подшипник распредвала',
    'Camshaft Seal': 'Сальник распредвала',
    'Camshaft Sprocket': 'Звезда распредвала',
    'Timing Chain': 'Цепь ГРМ',
    'Timing Chain Guide': 'Направляющая цепи ГРМ',
    'Timing Chain Tensioner': 'Натяжитель цепи ГРМ',
    'Timing Belt': 'Ремень ГРМ',
    'Timing Belt Tensioner': 'Натяжитель ремня ГРМ',
    'Timing Belt Idler': 'Обводной ролик ремня ГРМ',
    'Valve': 'Клапан',
    'Intake Valve': 'Впускной клапан',
    'Exhaust Valve': 'Выпускной клапан',
    'Valve Spring': 'Пружина клапана',
    'Valve Retainer': 'Опора пружины клапана',
    'Valve Keeper': 'Сухарь клапана',
    'Valve Stem Seal': 'Сальник клапана',
    'Valve Guide': 'Направляющая втулка клапана',
    'Valve Seat': 'Седло клапана',
    'Rocker Arm': 'Коромысло',
    'Rocker Arm Shaft': 'Ось коромысел',
    'Lifter': 'Толкатель',
    'Hydraulic Lifter': 'Гидрокомпенсатор',
    'Pushrod': 'Толкатель',
    'OHC': 'Верхний распредвал',
    'DOHC': 'Два верхних распредвала',
    'SOHC': 'Один верхний распредвал',
    'OHV': 'Нижний распредвал',
    'Variable Valve Timing': 'Переменное газораспределение',
    'VVT': 'VVT',
    'VTEC': 'VTEC',
    'VANOS': 'VANOS',
    'VCT': 'VCT',
    'Water Pump': 'Водяной насос',
    'Water Pump Gasket': 'Прокладка водяного насоса',
    'Thermostat': 'Термостат',
    'Thermostat Housing': 'Корпус термостата',
    'Thermostat Gasket': 'Прокладка термостата',
    'Radiator': 'Радиатор',
    'Radiator Fan': 'Вентилятор радиатора',
    'Radiator Fan Shroud': 'Кожух вентилятора радиатора',
    'Radiator Fan Clutch': 'Муфта вентилятора радиатора',
    'Radiator Hose': 'Шланг радиатора',
    'Upper Radiator Hose': 'Верхний шланг радиатора',
    'Lower Radiator Hose': 'Нижний шланг радиатора',
    'Heater Hose': 'Шланг отопителя',
    'Heater Core': 'Радиатор отопителя',
    'Heater Control Valve': 'Клапан отопителя',
    'Expansion Tank': 'Расширительный бачок',
    'Coolant Recovery Tank': 'Бачок для охлаждающей жидкости',
    'Coolant Temperature Sensor': 'Датчик температуры охлаждающей жидкости',
    'Coolant Level Sensor': 'Датчик уровня охлаждающей жидкости',
    'Radiator Cap': 'Крышка радиатора',
    'Coolant': 'Охлаждающая жидкость',
    'Antifreeze': 'Антифриз',
    'Fuel System': 'Топливная система',
    'Fuel Tank': 'Топливный бак',
    'Fuel Tank Sender': 'Датчик уровня топлива',
    'Fuel Pump': 'Топливный насос',
    'Fuel Pump Module': 'Модуль топливного насоса',
    'Fuel Pump Assembly': 'Топливный насос в сборе',
    'Fuel Filter': 'Топливный фильтр',
    'Fuel Strainer': 'Сетка топливного насоса',
    'Fuel Injector': 'Топливная форсунка',
    'Fuel Rail': 'Топливная рампа',
    'Fuel Pressure Regulator': 'Регулятор давления топлива',
    'Fuel Pressure Sensor': 'Датчик давления топлива',
    'Fuel Line': 'Топливная линия',
    'Fuel Hose': 'Топливный шланг',
    'Fuel Return Line': 'Возвратная топливная линия',
    'Fuel Filler Neck': 'Горловина топливного бака',
    'Fuel Cap': 'Крышка топливного бака',
    'Gas Cap': 'Крышка топливного бака',
    'Fuel Tank Vent Valve': 'Клапан вентиляции топливного бака',
    'EVAP Canister': 'Адсорбер',
    'EVAP Purge Valve': 'Клапан продувки адсорбера',
    'EVAP Vent Valve': 'Клапан вентиляции адсорбера',
    'Charcoal Canister': 'Угольный адсорбер',
    'Vapor Canister': 'Паровой адсорбер',
    'Air Intake System': 'Система впуска воздуха',
    'Air Filter': 'Воздушный фильтр',
    'Air Filter Housing': 'Корпус воздушного фильтра',
    'Air Intake Hose': 'Шланг воздухозаборника',
    'Air Intake Tube': 'Трубка воздухозаборника',
    'Air Intake Duct': 'Канал воздухозаборника',
    'Mass Air Flow Sensor': 'Датчик расхода воздуха',
    'MAF Sensor': 'Датчик MAF',
    'MAP Sensor': 'Датчик MAP',
    'Manifold Absolute Pressure Sensor': 'Датчик абсолютного давления в коллекторе',
    'Throttle Body': 'Дроссельная заслонка',
    'Electronic Throttle Body': 'Электронная дроссельная заслонка',
    'Throttle Position Sensor': 'Датчик положения дроссельной заслонки',
    'TPS': 'TPS',
    'Idle Air Control Valve': 'Клапан регулировки холостого хода',
    'IAC Valve': 'Клапан IAC',
    'Idle Control Valve': 'Клапан холостого хода',
    'Intake Manifold': 'Впускной коллектор',
    'Intake Manifold Gasket': 'Прокладка впускного коллектора',
    'Plenum': 'Пленум',
    'Intake Runner': 'Патрубок впускного коллектора',
    'Exhaust System': 'Система выхлопа',
    'Exhaust Manifold': 'Выпускной коллектор',
    'Exhaust Manifold Gasket': 'Прокладка выпускного коллектора',
    'Header': 'Паук',
    'Catalytic Converter': 'Катализатор',
    'Catalyst': 'Катализатор',
    'Pre-Cat': 'Предварительный катализатор',
    'Main Cat': 'Основной катализатор',
    'Resonator': 'Резонатор',
    'Muffler': 'Глушитель',
    'Exhaust Pipe': 'Выхлопная труба',
    'Downpipe': 'Приемная труба',
    'Mid-Pipe': 'Средняя труба',
    'Tailpipe': 'Концевая труба',
    'Exhaust Tip': 'Насадка на выхлоп',
    'Flex Pipe': 'Гибкая труба',
    'Exhaust Clamp': 'Хомут выхлопной системы',
    'Exhaust Hanger': 'Подвеска выхлопной системы',
    'Exhaust Gasket': 'Прокладка выхлопной системы',
    'Oxygen Sensor': 'Лямбда-зонд',
    'O2 Sensor': 'Лямбда-зонд',
    'Pre-Cat O2 Sensor': 'Лямбда-зонд перед катализатором',
    'Post-Cat O2 Sensor': 'Лямбда-зонд после катализатора',
    'Upstream O2 Sensor': 'Лямбда-зонд перед катализатором',
    'Downstream O2 Sensor': 'Лямбда-зонд после катализатора',
    'Air Fuel Ratio Sensor': 'Датчик состава топливовоздушной смеси',
    'AFR Sensor': 'Датчик AFR',
    'Wideband O2 Sensor': 'Широкополосный лямбда-зонд',
    'EGR System': 'Система EGR',
    'EGR Valve': 'Клапан EGR',
    'EGR Cooler': 'Охладитель EGR',
    'EGR Tube': 'Трубка EGR',
    'EGR Pressure Sensor': 'Датчик давления EGR',
    'EGR Temperature Sensor': 'Датчик температуры EGR',
    'PCV System': 'Система вентиляции картера',
    'PCV Valve': 'Клапан PCV',
    'Crankcase Ventilation Valve': 'Клапан вентиляции картера',
    'Breather Hose': 'Дыхательный шланг',
    'Breather Filter': 'Фильтр вентиляции картера',
    'Turbocharger': 'Турбокомпрессор',
    'Turbo': 'Турбокомпрессор',
    'Twin Turbo': 'Две турбины',
    'Bi-Turbo': 'Две турбины',
    'Supercharger': 'Компрессор',
    'ProCharger': 'Прокомпрессор',
    'Roots Supercharger': 'Рутс-компрессор',
    'Centrifugal Supercharger': 'Центробежный компрессор',
    'Intercooler': 'Интеркулер',
    'Charge Air Cooler': 'Охладитель наддувочного воздуха',
    'Aftercooler': 'Охладитель',
    'Intercooler Pipe': 'Трубка интеркулера',
    'Intercooler Hose': 'Шланг интеркулера',
    'Wastegate': 'Водяной затвор',
    'Blow Off Valve': 'Клапан сброса давления',
    'BOV': 'BOV',
    'Diverter Valve': 'Перепускной клапан',
    'Boost Controller': 'Контроллер наддува',
    'Boost Gauge': 'Указатель наддува',
    'Air Intake': 'Воздухозаборник',
    'Cold Air Intake': 'Холодный воздухозаборник',
    'Short Ram Intake': 'Короткий воздухозаборник',
    'Ram Air': 'Рам-воздух',
    'Ignition System': 'Система зажигания',
    'Ignition Coil': 'Катушка зажигания',
    'Coil On Plug': 'Катушка на свече',
    'COP': 'COP',
    'Distributor': 'Распределитель зажигания',
    'Distributor Cap': 'Крышка распределителя',
    'Rotor': 'Ротор',
    'Spark Plug Wire': 'Провод свечи зажигания',
    'Ignition Wire': 'Провод зажигания',
    'Spark Plug': 'Свеча зажигания',
    'Iridium Spark Plug': 'Иридиевая свеча зажигания',
    'Platinum Spark Plug': 'Платиновая свеча зажигания',
    'Copper Spark Plug': 'Медная свеча зажигания',
    'Spark Plug Gap': 'Зазор свечи зажигания',
    'Ignition Module': 'Модуль зажигания',
    'Igniter': 'Игнитер',
    'Crankshaft Position Sensor': 'Датчик положения коленвала',
    'CKP Sensor': 'Датчик CKP',
    'Camshaft Position Sensor': 'Датчик положения распредвала',
    'CMP Sensor': 'Датчик CMP',
    'Knock Sensor': 'Датчик детонации',
    'KS': 'KS',
    'Engine Control Module': 'Модуль управления двигателем',
    'ECM': 'ECM',
    'ECU': 'ECU',
    'PCM': 'PCM',
    'Powertrain Control Module': 'Модуль управления силовым агрегатом',
    'Engine Computer': 'Компьютер двигателя',
    'Engine Wiring Harness': 'Проводка двигателя',
    'Engine Sensor': 'Датчик двигателя',
    'Fuel Injection System': 'Система впрыска топлива',
    'Electronic Fuel Injection': 'Электронный впрыск топлива',
    'EFI': 'EFI',
    'Multi-Port Fuel Injection': 'Многоточечный впрыск топлива',
    'MPFI': 'MPFI',
    'Direct Fuel Injection': 'Прямой впрыск топлива',
    'GDI': 'GDI',
    'Fuel Rail': 'Топливная рампа',
    'Fuel Injector': 'Топливная форсунка',
    'Fuel Pressure Regulator': 'Регулятор давления топлива',
    'Fuel Pressure Sensor': 'Датчик давления топлива',
    'Fuel Pump': 'Топливный насос',
    'High Pressure Fuel Pump': 'Топливный насос высокого давления',
    'HPFP': 'HPFP',
    'Low Pressure Fuel Pump': 'Топливный насос низкого давления',
    'Starting System': 'Система запуска',
    'Battery': 'Аккумулятор',
    'Car Battery': 'Автомобильный аккумулятор',
    'Lead Acid Battery': 'Свинцово-кислотный аккумулятор',
    'AGM Battery': 'AGM аккумулятор',
    'Lithium Battery': 'Литий-ионный аккумулятор',
    'Battery Terminal': 'Клемма аккумулятора',
    'Battery Cable': 'Провод аккумулятора',
    'Battery Tray': 'Поддон аккумулятора',
    'Battery Hold Down': 'Крепление аккумулятора',
    'Starter': 'Стартер',
    'Starter Motor': 'Стартер',
    'Starter Solenoid': 'Соленоид стартера',
    'Starter Relay': 'Реле стартера',
    'Ignition Switch': 'Выключатель зажигания',
    'Ignition Key': 'Ключ зажигания',
    'Key Fob': 'Брелок',
    'Keyless Entry': 'Бесключевой доступ',
    'Remote Start': 'Дистанционный запуск',
    'Push Button Start': 'Запуск кнопкой',
    'Smart Key': 'Смарт-ключ',
    'Proximity Key': 'Ключ с бесключевым доступом',
    'Charging System': 'Система зарядки',
    'Alternator': 'Генератор',
    'Alternator Pulley': 'Шкив генератора',
    'Alternator Belt': 'Ремень генератора',
    'Serpentine Belt': 'Поликлиновой ремень',
    'Drive Belt': 'Приводной ремень',
    'V-Belt': 'Клиновой ремень',
    'Belt Tensioner': 'Натяжитель ремня',
    'Idler Pulley': 'Обводной ролик',
    'Voltage Regulator': 'Регулятор напряжения',
    'Electrical System': 'Электрическая система',
    'Fuse': 'Предохранитель',
    'Fuse Box': 'Блок предохранителей',
    'Relay': 'Реле',
    'Relay Box': 'Блок реле',
    'Wiring Harness': 'Проводка',
    'Wire': 'Провод',
    'Connector': 'Разъем',
    'Plug': 'Штекер',
    'Socket': 'Гнездо',
    'Switch': 'Переключатель',
    'Button': 'Кнопка',
    'Sensor': 'Датчик',
    'Actuator': 'Привод',
    'Solenoid': 'Соленоид',
    'Motor': 'Мотор',
    'Generator': 'Генератор',
    'Wiper System': 'Система стеклоочистителей',
    'Windshield Wiper': 'Стеклоочиститель',
    'Wiper Motor': 'Мотор стеклоочистителя',
    'Wiper Arm': 'Рычаг стеклоочистителя',
    'Wiper Blade': 'Щетка стеклоочистителя',
    'Wiper Refill': 'Резинка щетки стеклоочистителя',
    'Wiper Linkage': 'Тяга стеклоочистителя',
    'Wiper Switch': 'Переключатель стеклоочистителя',
    'Washer System': 'Система омывателя',
    'Washer Pump': 'Насос омывателя',
    'Washer Reservoir': 'Бачок омывателя',
    'Washer Fluid': 'Жидкость омывателя',
    'Washer Nozzle': 'Форсунка омывателя',
    'Washer Hose': 'Шланг омывателя',
    'Horn': 'Сигнал',
    'Horn Relay': 'Реле сигнала',
    'Horn Button': 'Кнопка сигнала',
    'Lighting System': 'Система освещения',
    'Headlight': 'Фара',
    'Headlight Assembly': 'Фара в сборе',
    'Headlight Housing': 'Корпус фары',
    'Headlight Lens': 'Стекло фары',
    'Headlight Bulb': 'Лампа фары',
    'Headlight Socket': 'Гнездо лампы фары',
    'Headlight Wiring': 'Проводка фар',
    'Headlight Switch': 'Выключатель фар',
    'Headlight Relay': 'Реле фар',
    'Dimmer Switch': 'Переключатель дальнего/ближнего света',
    'High Beam': 'Дальний свет',
    'Low Beam': 'Ближний свет',
    'Daytime Running Light': 'Дневные ходовые огни',
    'DRL': 'DRL',
    'Fog Light': 'Противотуманная фара',
    'Fog Lamp': 'Противотуманная фара',
    'Driving Light': 'Прожектор',
    'Off-Road Light': 'Внедорожная фара',
    'Light Bar': 'Световая балка',
    'Tail Light': 'Задний фонарь',
    'Taillight': 'Задний фонарь',
    'Rear Light': 'Задний фонарь',
    'Tail Light Assembly': 'Задний фонарь в сборе',
    'Tail Light Lens': 'Стекло заднего фонаря',
    'Tail Light Bulb': 'Лампа заднего фонаря',
    'Reverse Light': 'Фонарь заднего хода',
    'Back Up Light': 'Фонарь заднего хода',
    'Brake Light': 'Стоп-сигнал',
    'Third Brake Light': 'Дополнительный стоп-сигнал',
    'Center High Mount Stop Light': 'Дополнительный стоп-сигнал',
    'CHMSL': 'CHMSL',
    'Turn Signal': 'Повторитель поворота',
    'Turn Signal Light': 'Указатель поворота',
    'Blinker': 'Повторитель поворота',
    'Side Marker Light': 'Боковой габарит',
    'Side Marker': 'Боковой габарит',
    'Parking Light': 'Габаритный огонь',
    'License Plate Light': 'Фонарь подсветки номера',
    'License Lamp': 'Фонарь подсветки номера',
    'Interior Light': 'Салонный свет',
    'Dome Light': 'Плафон',
    'Map Light': 'Лампа для карты',
    'Reading Light': 'Лампа для чтения',
    'Footwell Light': 'Подсветка ног',
    'Door Light': 'Подсветка двери',
    'Trunk Light': 'Подсветка багажника',
    'Glove Box Light': 'Подсветка бардачка',
    'Vanity Mirror Light': 'Подсветка зеркала в козырьке',
    'Ambient Light': 'Атмосферная подсветка',
    'LED': 'LED',
    'Light Emitting Diode': 'Светодиод',
    'HID': 'HID',
    'High Intensity Discharge': 'Гидрогенидная лампа',
    'Xenon': 'Ксенон',
    'Halogen': 'Галоген',
    'Incandescent': 'Лампа накаливания',
    'Bulb': 'Лампа',
    'Light Bulb': 'Лампа',
    'Headlight Bulb': 'Лампа фары',
    'Tail Light Bulb': 'Лампа заднего фонаря',
    'Fog Light Bulb': 'Лампа противотуманной фары',
    'Turn Signal Bulb': 'Лампа повторителя поворота',
    'Brake Light Bulb': 'Лампа стоп-сигнала',
    'Reverse Light Bulb': 'Лампа заднего хода',
    'License Plate Bulb': 'Лампа подсветки номера',
    'Interior Bulb': 'Лампа салона',
    'Socket': 'Гнездо',
    'Pigtail': 'Провод с разъемом',
    'HID Ballast': 'Балласт HID',
    'Xenon Ballast': 'Балласт ксенона',
    'Headlight Leveling Sensor': 'Датчик уровня фар',
    'Headlight Washer': 'Омыватель фар',
    'Headlight Wiper': 'Стеклоочиститель фар',
    'Heating and Air Conditioning': 'Отопление и кондиционирование',
    'HVAC': 'HVAC',
    'Heating Ventilation and Air Conditioning': 'Отопление, вентиляция и кондиционирование',
    'Air Conditioning': 'Кондиционер',
    'AC': 'Кондиционер',
    'AC Compressor': 'Компрессор кондиционера',
    'Compressor': 'Компрессор',
    'AC Condenser': 'Конденсатор кондиционера',
    'Condenser': 'Конденсатор',
    'AC Evaporator': 'Испаритель кондиционера',
    'Evaporator': 'Испаритель',
    'AC Receiver Drier': 'Ресивер-осушитель кондиционера',
    'Receiver Drier': 'Ресивер-осушитель',
    'AC Accumulator': 'Аккумулятор кондиционера',
    'Accumulator': 'Аккумулятор',
    'AC Expansion Valve': 'Расширительный клапан кондиционера',
    'Expansion Valve': 'Расширительный клапан',
    'AC Orifice Tube': 'Дроссельная трубка кондиционера',
    'Orifice Tube': 'Дроссельная трубка',
    'AC Hose': 'Шланг кондиционера',
    'AC Line': 'Линия кондиционера',
    'AC Pipe': 'Трубка кондиционера',
    'AC Discharge Hose': 'Шланг нагнетания кондиционера',
    'AC Suction Hose': 'Шланг всасывания кондиционера',
    'AC Liquid Line': 'Жидкостная линия кондиционера',
    'AC Service Valve': 'Сервисный клапан кондиционера',
    'Schrader Valve': 'Клапан Шредера',
    'AC Pressure Switch': 'Датчик давления кондиционера',
    'AC Pressure Sensor': 'Датчик давления кондиционера',
    'Heater Core': 'Радиатор отопителя',
    'Heater Valve': 'Клапан отопителя',
    'Heater Hose': 'Шланг отопителя',
    'Blower Motor': 'Мотор вентилятора',
    'Blower Motor Resistor': 'Резистор мотора вентилятора',
    'Blower Motor Fan': 'Вентилятор мотора вентилятора',
    'Blower Motor Cage': 'Крыльчатка мотора вентилятора',
    'AC Control Panel': 'Панель управления кондиционером',
    'AC Control Head': 'Панель управления кондиционером',
    'Climate Control': 'Климат-контроль',
    'Automatic Climate Control': 'Автоматический климат-контроль',
    'Dual Zone Climate Control': 'Двухзонный климат-контроль',
    'Tri Zone Climate Control': 'Трехзонный климат-контроль',
    'Temperature Door Actuator': 'Привод заслонки температуры',
    'Mode Door Actuator': 'Привод заслонки режима',
    'Blend Door Actuator': 'Привод заслонки смешения',
    'Recirculation Door Actuator': 'Привод заслонки рециркуляции',
    'Fresh Air Door Actuator': 'Привод заслонки свежего воздуха',
    'Cabin Air Filter': 'Фильтр салона',
    'Pollen Filter': 'Фильтр пыльцы',
    'HVAC Filter': 'Фильтр HVAC',
    'Charcoal Cabin Filter': 'Угольный фильтр салона',
    'Heater Control Panel': 'Панель управления отопителем',
